---
title: "How to run an effective meeting"
description: |
  Guidelines and suggestions for running effective meetings.
author:
  - name: Alisa Devedzic Kjærgaard 
    affiliations:
      - name: Steno Diabetes Center Aarhus
        url: https://stenoaarhus.dk
---

{{< include ../../includes/_wip.md >}}

Effective meetings have a potential to improve productivity and work
satisfaction and inspire greater collaboration.

## Types of meetings

-   *Onboarding meetings* can help people understand the organization's
    structure, what projects are coming up, how their role and work will
    fit into the broader picture, and to set early expectations for what
    the person should do in their first few weeks and months, and how
    they fit into the big picture.
-   *Brainstorming meetings*
-   *Kickoff meetings* are a good way to start a project and fill
    everyone in.
-   *Feedback and retrospective meetings* evaluate the process: what
    went well, what didn't, how to proceed and what will be changed for
    the next project.

## Meeting category by aims

-   *Decision-making*: The aim is for decision makers to come to a
    conclusion that leads to action. Consider the number of participants
    (fewer is better than more) and their competences (whose opinions
    and expertise are relevant to the problem).
-   *Information sharing*: The objective is to spread awareness to a
    broader team. Consider using another platform than meeting to share
    this information, e.g., Slack, Trello, etc
-   *Problem-solving*: The goal is to crowdsource advice and build a
    plan based on that knowledge, such as by discussing ways to optimize
    an experimental set-up.
-   *Discussion*: The purpose is to exchange perspectives on a topic,
    such as by discussing the implications of a recently published
    paper.

## Meeting rules

-   Arrive on time
-   Come prepared
-   Keep an open mind and a positive attitude
-   Actively listen to opinions and presentations of others
-   Do not interrupt
-   Do not monopolize talking time and do not dominate the meeting
    (facilitator's role to help with this)
-   Actively participate
-   Aim to reach consensus

## Before the meeting

-   Make sure that everybody is familiar with the code of conduct and
    meeting rules.
-   Make a meeting agenda, including time-frame (this lets people know
    what to expect).
-   Assign people roles before the meeting starts:
    -   A facilitator should keep people on track, summarize after each
        topic and clarify next steps.
    -   A note taker is responsible for documenting and distributing
        clear and concise minutes.
    -   Presenters and other relevant participants should be notified of
        their expected roles beforehand, so they meet prepared.
-   Consider the medium (either virtual or in-person, and if so, room
    size, lighting, temperature, chairs), time of the day, refreshments,
    etc.
-   Organizer meets early and ensures that all the relevant materials
    (paper, pens, sticky notes, etc) and technical equipment (PC,
    projector, camera, etc) are present and functioning.

## At the meeting

-   Start meetings on time even if not everybody has arrived.
-   Consider banning distractions (laptops/tablets/phones) from
    meetings.
-   Consider starting with a brief icebreaker or a quick check-in on
    everyone's day or week (however, details on Trello or similar).
-   Consider asking for topics to be put on AOB (any other business) at
    the very beginning of the meeting, so everybody has some time to
    prepare for a potential surprise.
-   If the meeting is part of a series, it is probably relevant to
    follow-up on last meeting, including progress (action items).
-   Plan to engage people or check in on attendees often (examples
    below). Have people write down their questions during the meeting.
    Collect them and go over them as a group. This can help introverts,
    or those who don't feel comfortable speaking up, get their concerns
    addressed. Break people into groups and have them accomplish small
    tasks, or make decisions, together. Then have them share their
    findings with the larger group. Break the meeting into sections with
    a different person leading each section or part of the agenda.
    Switching up presenters helps refresh people's attention span and
    encourages attendees to feel ownership over a topic or project.
-   A facilitator should keep people on track (parking lot for off-topic
    ideas), summarize after each topic and assign action items (owners,
    due date and follow-up).
-   A note taker is responsible for documenting clear and concise
    minutes.
-   End the meeting if all topics are handled, even if it is ahead of
    schedule.
-   Leave meeting with a review of clear action items, due dates, and
    owners.

## After the meeting

-   Note taker deposits the recorded minutes on a designated platform,
    e.g., Trello, common docs, etc, so these are available to everybody
    who could and could not attend (preferably within 2-3 hours).
-   Evaluation (feedback, anonymous?)

## References

-   [How to run effective meetings: Five principles for getting more
    done as a
    team](https://slack.com/intl/en-dk/blog/productivity/run-effective-meetings)
-   [The 11-step guide to running effective
    meetings](https://www.nature.com/articles/d41586-019-02295-z)
-   [Seven Steps to Running the Most Effective Meeting
    Possible](https://www.forbes.com/sites/forbesleadershipforum/2014/02/05/seven-steps-to-running-the-most-effective-meeting-possible/)
