---
title: "General Code of Conduct"
description: |
  Material and resources for Conduct during events, meetings, and online spaces.
# author:
#   - name: Luke W. Johnston
#     url: https://lukewjohnston.com
#     affiliation: Steno Diabetes Center Aarhus
#     affiliation_url: https://stenoaarhus.dk
date: "`r Sys.Date()`"
---

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

# Expected Behavior
We treat each other with respect and courtesy, whether it be online or in-person. In order to foster trust, a positive and professional learning environment, strengthen collaboration and contribute to a positive working environment, we encourage the following kinds of behaviours in all interactions:

- Show courtesy and respect towards others.
- Be kind and aware of your words.
- Use welcoming and inclusive language.
- Be respectful of different viewpoints and experiences.
- Gracefully accept constructive criticism.
- Focus on what is best for the community overall.

Read the ["four social rules"](https://www.recurse.com/manual#sub-sec-social-rules) for further recommendations and details on proper behaviour. These rules are more lightweight, and we have all broken them, which is why awareness is important. A sincere apology for breaking these rules goes a long way.

# Unacceptable Behavior

Examples of unacceptable behavior include, but are not limited to:

- Written or verbal comments which have the effect of excluding people on the basis of membership of any specific group.
- Causing someone to fear for their safety, such as through stalking, following, or intimidation.
- Violent threats or language directed against another person.
- Displays of sexual or violent images.
- Unwelcome sexual attention.
- Non-consensual or unwelcome physical contact.
- Sustained disruption of talks, events, or communications.
- Insults or put-downs.
- Sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes.
- Excessive swearing.
- Incitement to violence, suicide, or self-harm.
- Continuing to initiate interaction (including photography or recording) with someone after being asked to stop.
- Publication of private communication without consent.

# Consequences of Unacceptable Behavior

If you are not comfortable confronting the violator yourself, either privately or in public, seek help from peers and/or supervisor(s) you trust.
<!--  Comment:
Uncomment after adding link to consequences. 
Unacceptable behavior is not tolerated and if continued may lead to ...
--> 

<!-- TODO: the region has an e-dok instruction on harassment. Add the e-dok here. -->
