---
title: "Administrative and legal demands in research"
---

# Clinical studies

* Preparing for a study
            * 1.1.1 Research within the region (AUH) or University (AU)?
            * 1.1.2 Report to VEK (obs research biobank vs biobank, research in children and whole genome issues)
            * 1.1.3 Clinical Trials (report to clinicaltrials.gov and the Danish Medicines Agency (Lægemiddelstyrelsen))
         
      * 1.2. Lab used?
            * 1.2.1 M-lab
            * 1.2.2 Patolab
            * 1.2.3 Collaborating with dep. of biochemistry (klinisk biokemisk)
      
      * 1.3. Biobank
      
 
# Access to patient data (not through Statistics Denmark)
      * 2.1 Research project or quality control study
      
      * 2.2 Research project using Patient Data
            * 2.2.1 Report to Styrelsen for patientsikkerhed - obs blev dette ændret
            * 2.2.2 Attachment to the department where the patient data is being collected (get a unpaid job...)
      
      * 2.3 Quality control study
            * 2.3.1 Aquire permission from head of department
      

# Report to Danish Data Authorities (Datatilsynet - Paraply anmeldelse under RM eller via AU)
      * 3.1 Report to RM
            * 3.1.2 Obs Requires acces to a RM computer (https://www.rm.dk/sundhed/faginfo/forskning/Forskningsprojekter/)
      
      * 3.2 Report to AU
            * 3.2.1 https://medarbejdere.au.dk/informationssikkerhed/databeskyttelse/saerligt-om-forskning/anmeldelsesskema-dataansvarlig/
     
 
# GDPR
      * 4.1 Link to GDPR info: https://medarbejdere.au.dk/informationssikkerhed/databeskyttelse/
 
 
# Datastorage of sensitive patient data
      * 5.1 Storage at AU
            * 5.1.1 Patient and trial data (patient sensitive): RedCap
            * 5.1.2 Larger data files: O-drive, needs to be setup through AU-IT so that logging is possible. Only pseudonymized patient data.
            * 5.1.3 Link to AU datastorage info: https://medarbejdere.au.dk/informationssikkerhed/klassifikation-af-data/#c2545048
      
      * 5.2 Storage at RM
            * 5.2.1 Patient and trial data (patient sensitive): RedCap through RM
            * 5.2.2 Larger data files: MidtX, needs to be setup through RM-IT so that logging is possible.  


# Datahandling agreements.......
