---
title: Booking meeting rooms at Forum
description: |
  How to book rooms for meetings in the Forum building at AUH.
author:
  - name: Luke W. Johnston
    affiliations: 
      - name: Steno Diabetes Center Aarhus
        url: https://stenoaarhus.dk
---

{{< include ../../includes/_wip.md >}}

Booking rooms in Forum is fairly easy *if you know how to do it*. But it
is not a straight forward way to find out.

If you have a Region email and have Outlook installed, the easiest
approach to booking rooms is through the Outlook calendar. But not
everyone has Outlook or don't want to use multiple calendars, like if
they are employed at Aarhus University but with an affiliation with the
Region.

The next way of booking rooms is through the [Citrix
Portal](https://citrixportal.rm.dk), which you can only access if you
have a Region ID. After you log into Citrix, use the Search button on
the top right corner to look for `Pronestor`.

When it shows itself on the screen, click the icon for Pronestor. After
it opens up, you should see a list of dates. Select the date you want to
book by clicking the button "Ny mødebestilling". You'll be given a list
of rooms to book. Select the start time ("start") and end time ("slut")
at the top, then click the room that is available. Afterwards, continue
by clicking the "Check ud" at the top.

That's it, you've booked the room!
