---
title: "Welcome and getting started"
description: Material for onboarding new researchers at SDCA.
order: 1
author:
    # Order alphabetical by last name
  - name: Daniel B. Ibsen
    affiliations: 
      - ref: sdca
      - ref: ph-au
  - name: Tinne Laurberg
    affiliations: 
      - ref: sdca
metadata-files: 
  - ../../_affiliations.yml
---

{{< include ../../includes/_wip.md >}}

## Welcome!!

We have high ambitions at SDCA. We believe that people with diabetes can
have a good life. We will make a difference to all people with or at
risk of getting diabetes in Central Denmark Region.

As a new member of our research team, there is a lot of things you need
learn about the organization, the culture (both research and social) and
a lot of practical stuff. The page here is thought of as your initial
entry point, where you can get an overview. This is also an atlas for
you to return to when you need to look up specific information.

To get an introduction to the research team and this document you will
be teamed up with an experienced member from research. It is your
supervisor's responsibility to find you a "buddy." Please ask your
supervisor if this is not already in place.

Your buddy will walk you through the relevant tables below and give you
an overview of all the topics that you need to be aware of. The agenda
for the meeting is:

1.  Introduce yourselves
2.  Go through the table below
3.  Take a tour around the research facility
4.  Arrange follow-up talk

The purpose of the follow-up talk is to catch up on how you have settled
in. If you have any specific questions you can also ask them. As the
final thing, you and your buddy will evaluate the introduction. You will
be given responsibility to update this website if you have encountered
any information that was not up to date and you should add any other
information you would have liked the page to contain. This is a very
important step because it ensures that this material is always current
and helps the next new team member.

Read through this website, especially the "Onboarding" section, which is
targeted to new employees. If you have a question that isn't answered
here, open an
[Issue](https://github.com/steno-aarhus/research/issues/new) (needs a
[GitHub](https://github.com/join) account) to let us know that we need
to add this information. Then email either Inger Hornbech
([inger.hornbech\@rm.dk](mailto:inger.hornbech@rm.dk){.email}) or Julie
Knudsen ([julie.knudsen\@rm.dk](mailto:julie.knudsen@rm.dk){.email}) to
get your question (hopefully) answered.

## Practicalities

Access/ID card

:   If you need access to Forum, its best that you get an access card.

    -   If you have an RM ID-card: You can get access to SDCA by
        emailing your User ID to Inger Hornbech or Julie Knudsen.
    -   If you don't have an RM ID-card: Inger or Julie will need your
        CPR number and after that you will need to visit the card
        administration to have a photo taken, which is at Plan 1,
        Universitetstorvet i Nord, Krydspunkt 110, room J116-106.
        Opening hours are Mon to Fri from 07.30-09.30 & 10.00-12.00.
        Remember to bring photo ID (e.g. driver's license).

Printer

:   Note the name of the printer from someone in your office. For
    questions regarding the SDCA printer: ask Maria Siggaard
    ([marsig\@rm.dk](mailto:marsig@rm.dk){.email}). For questions
    regarding the AU printer: ask Karin Ørbæk Kristensen
    ([karin\@clin.au.dk](mailto:karin@clin.au.dk){.email}) or Charlotte
    Rosholm ([cro\@clin.au.dk](mailto:cro@clin.au.dk){.email}).

Microsoft Office templates (for RM)

:   All templates are found in the folder
    `N:\Afdeling\AUHSTDIC\_Fælles\SDCA-dokumenter_Skabeloner`. This
    (unfortunately) can so far only be accessed through the
    ["Citrixportal"](https://citrixportal.rm.dk).

Office supplies

:   You can find office supplies in the copy room on Plan 3 at SDCA in
    Forum. If something you need isn't there, contact Julie Knudsen at
    [julie.knudsen\@rm.dk](mailto:julie.knudsen@rm.dk){.email}.

Letters and other mail

:   For sending mail, contact Inger Hornbech
    ([inger.hornbech\@rm.dk](mailto:inger.hornbech@rm.dk){.email}).

MasterCard

:   At RM, it's only the managers who have a Mastercard. At SDCA Head of
    Research Niels Jessen has one. Contact Maria Siggaard
    ([marsig\@rm.dk](mailto:marsig@rm.dk){.email}) if you need to buy
    something by using the MasterCard. For those affiliated through
    Aarhus University, you can
    [apply](https://medarbejdere.au.dk/en/administration/finance/travel-booking/policy-for-credit-card-at-aarhus-university/)
    for an employee MasterCard.

## General information

Calling in sick Depends on your terms of employment. PhD etc.: email
your supervisor. Postdoc etc. at SDCA: email Inger Hornbech
(inger.hornbech\@rm.dk) for registration if you have an RM employment.
If you are employed by AU please contact Charlotte Rosholm
(cro\@clin.au.dk) or Karin Ørbæk Kristensen (karin\@clin.au.dk). Please
refer to the one who administers yours or your supervisor's grants.

Holiday, days off, "first day with sick child" and "omsorgsdage" Depends
on your terms of employment. PhD etc.: email your supervisor. Postdoc
etc. in SDCA: email Inger Hornbech (inger.hornbech\@rm.dk) for
registration if you have an RM employment. For AU-related matters please
contact Charlotte Rosholm (cro\@clin.au.dk) or Karin Ørbæk Kristensen
(karin\@clin.au.dk). Please refer to the one who administers yours or
your supervisor's grants.

Maternity/paternity leave and other leaves Central Denmark Region
employment: ask Maria Siggaard (marsig\@rm.dk). AU employment: please
contact Charlotte Rosholm (cro\@clin.au.dk) or Karin Ørbæk Kristensen
(karin\@clin.au.dk). Please refer to the one who administers yours or
your supervisor's grants.

MUS talks MUS talks depend on one's terms of employment. Ask Maria
Siggaard, marsig\@rm.dk if you have questions regarding this.

Salary Contract. If you have question about a RM contract talk to Maria
Siggaard, marsig\@rm.dk. If you have a AU contract please contact
Charlotte Rosholm (cro\@clin.au.dk) or Karin Ørbæk Kristensen
(karin\@clin.au.dk). Please refer to the one who administers yours or
your supervisor's grants.
