---
title: "IT basics"
description: A general introduction to common IT topics when starting out.
date: last-modified
author:
    # Order alphabetical by last name
  - name: Daniel B. Ibsen
    affiliations: 
      - ref: sdca
  - name: Luke W. Johnston
    affiliations:
      - ref: sdca
      - ref: clin-au
  - name: Tinne Laurberg
    affiliations: 
      - ref: sdca
---

{{< include ../../includes/_wip.md >}}

IT software, services, and hardware are all dependent on your location
of employment: Aarhus University or Region Midt. Getting user access is
usually done as part of the employment process. Once you have a user ID,
here are some basic things you might need from IT.

## Institute-specific details

::: panel-tabset
### Aarhus University

Specific support can be found on their [Guides
website](https://medarbejdere.au.dk/en/administration/it/guides) or by
contacting them directly on their [contacts
page](https://medarbejdere.au.dk/en/administration/it/main-academic-areas/he-it-support/).
Their guides are all available in either English or Danish.

-   **WiFi**: Accessing internet is done with eduroam. Set up is done
    through their [guide](https://eduroam.au.dk/en/).
-   **VPN**: When working remotely, many university and research
    services are only available by connecting to the university VPN. Use
    their [Setup
    Guide](https://medarbejdere.au.dk/en/administration/it/guides/network/vpn-remoteaudk).
-   **Personal drive**: You can connect and access your personal drive
    from your computer by following these
    [instructions](https://medarbejdere.au.dk/en/administration/it/guides/datastorage/personal-folder-access/).
-   **Shared drive(s)**: If you need access to a shared drive that your
    team or colleagues use, start with first [requesting
    access](https://medarbejdere.au.dk/en/administration/it/guides/datastorage/access-to-shared-folder)
    to it. Once you get it, follow these
    [steps](https://medarbejdere.au.dk/en/administration/it/guides/datastorage/how-to-access-a-shared-folder)
    to access it on your computer.
-   **Email and calendar**: Setting up or accessing your email and
    calender is done by going through their [Email FAQ
    Guide](https://medarbejdere.au.dk/en/administration/it/guides/mail/faq-mail).

### Region Midt

Unlike Aarhus University, which is quite familiar and used to a diverse
set of IT needs and international employees, the Region doesn't have as
well developed and clear documentation for IT related topics.
Documentation is also entirely in Danish. Help, support, and most other
documents or services are almost completely only available through the
["Citrixportal"](https://citrixportal.rm.dk), which you need to log into
with your Region ID. Details about how to gain access is found either
[here](https://www.rm.dk/om-os/organisation/hjemmearbejde---for-medarbejdere/vejledning-til-fjernadgang-pa-sms/)
(if outside the Region intranet, you will need to follow this
[guide](https://www.rm.dk/om-os/organisation/hjemmearbejde---for-medarbejdere/vejledning-til-fjernadgang-pa-sms/)
to activate two-factor authentication codes).

-   **Personal drives**: Accessed by searching for "Stifinder" in the
    Citrix portal. Files saved to the Region personal drive are
    difficult to access outside of the Citrixportal and can't easily be
    shared with others who do not have a Region ID. So we **do not**
    recommend using the Region drives for anything but highly sensitive
    information. Data should not be saved on the personal drive, but
    instead should be saved through appropriate sources (depends on your
    research team).
-   **Shared drives**: Accessed by searching for "Stifinder Afdeling" in
    the Citrixportal. Like with the personal drive above, unless you
    need to save and share information that is highly sensitive, we
    recommend **not** to use the shared drive and instead use other
    sources (like GitHub or the Aarhus University shared drives).
-   **Email and calendar**: You can open your email and calendar either
    through the Citrixportal or by using
    [`post.rm.dk`](https://post.rm.dk/).
:::

Regardless of which institution is your administrative employer, if you
work primarily at SDCA, there are a number of helpful template files and
other resources found only in Citrix (by searching for "Stifinder
Afdeling"). We hope to slowly make these files more easily available,
but until then, you can find relevant ones by asking your colleagues.
